unique_ids:
  assets:
    standard-page.html: QK55CTXQ3X7T4TJNC2XBDMHMBGVQMYJO
    theme.css: O6BDK4KOPDNXTKJIK7YNAP4LAF5LSK6H
  forms:
    Form1: BQIX7SVKD3HU7ALMHEU2AVTYKBCMSAMC
  modules: {}
  scripts: {}
  server_modules: {}
